services:
  payway:
    build:
      context: .
      args:
        - BUILD_VERSION=1.0.0
    ports:
      - 3003:3003
    environment:
      - APP_ENV=test
    command: --bind 0.0.0.0:3003 --enable-openapi true
